version: '3'
services:
  game:
    image: "${DOCKER_REPOSITORY_URL}/cqmike/game:latest"
    env_file:
      - .env
    restart: always
    volumes:
      - $PWD/conf/:/app/etc/
    networks:
      - base-net


networks:
  base-net:
    external: true
