// Code generated by goctl. DO NOT EDIT.
package types

type ChangeWordReq struct {
	RoomId int64 `json:"roomId"`
}

type ChangeWordResp struct {
}

type CreateRoomReq struct {
	PlayerNum     int64 `json:"playerNum"`
	UndercoverNum int64 `json:"undercoverNum"`
	CivilianNum   int64 `json:"civilianNum"`
}

type CreateRoomResp struct {
	RoomId int64 `json:"roomId"`
}

type CreateUserReq struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type CreateUserResp struct {
	UserId int64 `json:"userId"`
}

type EliminateUserReq struct {
	RoomId int64 `json:"roomId"`
	UserId int64 `json:"userId"`
}

type EliminateUserResp struct {
}

type GameInfo struct {
	GameId            int64   `json:"gameId"`
	UndercoverWord    string  `json:"undercoverWord"`
	CivilianWord      string  `json:"civilianWord"`
	UndercoverUserIds []int64 `json:"undercoverUserIds"`
	CivilianUserIds   []int64 `json:"civilianUserIds"`
	EliminatedUserIds []int64 `json:"eliminatedUserIds"`
}

type GameOverReq struct {
	RoomId int64 `json:"roomId"`
}

type GameOverResp struct {
}

type JoinRoomReq struct {
	RoomId int64 `json:"roomId"`
}

type JoinRoomResp struct {
}

type QueryUserReq struct {
	UserId int64 `json:"userId"`
}

type QueryUserResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type Room struct {
	RoomId           int64    `json:"roomId"`
	PlayerNum        int64    `json:"playerNum"`
	UndercoverNum    int64    `json:"undercoverNum"`
	CivilianNum      int64    `json:"civilianNum"`
	HomeOwnersUserId int64    `json:"homeOwnersUserId"`
	Status           int64    `json:"status"`
	Users            []User   `json:"users"`
	Game             GameInfo `json:"game"`
}

type RoomInfoReq struct {
	RoomId int64 `json:"roomId"`
}

type RoomInfoResp struct {
	Room
}

type StartGameReq struct {
	RoomId int64 `json:"roomId"`
}

type StartGameResp struct {
	GameId            int64   `json:"gameId"`
	UndercoverWord    string  `json:"undercoverWord"`
	CivilianWord      string  `json:"civilianWord"`
	UndercoverUserIds []int64 `json:"undercoverUserIds"`
	CivilianUserIds   []int64 `json:"civilianUserIds"`
}

type UpdateUserReq struct {
	Nickname string `json:"nickname"`
}

type UpdateUserResp struct {
}

type User struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type WebSocketResponse struct {
}
